// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_agencia_viajes.Models;

namespace WebAPI_agencia_viajes.Migrations
{
    [DbContext(typeof(AgenciaViajesContext))]
    [Migration("20200112194721_migracion_enero_2020_2")]
    partial class migracion_enero_2020_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI_agencia_viajes.Models.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DireccionAgencia")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Nit");

                    b.Property<string>("NombreAgencia")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TelefonoAgencia")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Agencia");
                });

            modelBuilder.Entity("WebAPI_agencia_viajes.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgenciaId");

                    b.Property<string>("DireccionHotel")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NombreHotel")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TelefonoHotel")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("WebAPI_agencia_viajes.Models.TipoHabitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionTipo")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoHabitacion");
                });

            modelBuilder.Entity("WebAPI_agencia_viajes.Models.Hotel", b =>
                {
                    b.HasOne("WebAPI_agencia_viajes.Models.Agencia", "Agencia")
                        .WithMany("AgenciaHoteles")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
